// Auto-generated by build-geocache.js — do not edit
const GEOCACHE = {
  "edgefield primary school hall": {
    "lat": 1.4003512,
    "lng": 103.907493,
    "display": "Edgefield Primary School, 41, Edgefield Plains, Punggol Field, Punggol Field East, Punggol, North-east Region, Singapore, 828869, Singapore"
  },
  "edgefield secondary school hall": {
    "lat": 1.4001965,
    "lng": 103.9023095,
    "display": "Edgefield Secondary School, 36, Punggol Field, Matilda, Punggol Field West, Punggol, North-east Region, Singapore, 828814, Singapore"
  },
  "eunos primary school hall": {
    "lat": 1.3248169,
    "lng": 103.9043661,
    "display": "Eunos Primary School, 95, Jalan Eunos, Geylang East, Eunos, Geylang, Central Region, Singapore, 419529, Singapore"
  },
  "evergreen primary school hall": {
    "lat": 1.4438227,
    "lng": 103.7947141,
    "display": "Evergreen Primary School, 31, Woodlands Circle, Woodlands East, Admiralty, Woodlands, North Region, Singapore, 738908, Singapore"
  },
  "evergreen secondary school hall": {
    "lat": 1.4417392,
    "lng": 103.7940238,
    "display": "Evergreen Secondary School, 11, Woodlands Street 83, Midview, Admiralty, Woodlands, North Region, Singapore, 738489, Singapore"
  },
  "farrer park primary school hall": {
    "lat": 1.3123692,
    "lng": 103.8507914,
    "display": "Farrer Park Primary School, 2, Farrer Park Road, Kampong Java, Kallang, Central Region, Singapore, 217567, Singapore"
  },
  "fengshan primary school hall": {
    "lat": 1.3300987,
    "lng": 103.9318825,
    "display": "Fengshan Primary School, 307, Bedok North Road, Bedok North, Bedok, East Region, Singapore, 469680, Singapore"
  },
  "fuhua primary school hall": {
    "lat": 1.3364853,
    "lng": 103.7364545,
    "display": "Fuhua Primary School, 65, Jurong East Street 13, Yuhua East, Yuhua, Jurong East, West Region, Singapore, 609647, Singapore"
  },
  "gan eng seng primary school hall": {
    "lat": 1.2858762,
    "lng": 103.8152417,
    "display": "Gan Eng Seng Primary School, 100, Redhill Close, Redhill, Telok Blangah, Bukit Merah, Central Region, Singapore, 158901, Singapore"
  },
  "geylang methodist primary school hall": {
    "lat": 1.318445,
    "lng": 103.8841431,
    "display": "Geylang Methodist Primary School, Geylang East Central, Aljunied, Geylang, Central Region, Singapore, 380117, Singapore"
  },
  "gongshang primary school hall": {
    "lat": 1.357296,
    "lng": 103.9492763,
    "display": "Gongshang Primary School, 1, Tampines Street 42, Tampines East, Tampines, East Region, Singapore, 158901, Singapore"
  },
  "greendale primary school hall": {
    "lat": 1.3961911,
    "lng": 103.9126887,
    "display": "Greendale Primary School, 50, Edgedale Plains, Punggol Field, Punggol Field East, Punggol, North-east Region, Singapore, 828848, Singapore"
  },
  "greendale secondary school hall": {
    "lat": 1.397582,
    "lng": 103.9115751,
    "display": "Greendale Secondary School, 51, Edgedale Plains, Punggol Field, Punggol Field East, Punggol, North-east Region, Singapore, 828866, Singapore"
  },
  "greenridge primary school hall": {
    "lat": 1.3856168,
    "lng": 103.7680048,
    "display": "Greenridge Primary School, 11, Jelapang Road, Saujana, Bukit Panjang, West Region, Singapore, 677744, Singapore"
  },
  "greenridge secondary school hall": {
    "lat": 1.3753024,
    "lng": 103.7639957,
    "display": "Greenridge Secondary School, 31, Gangsa Road, Jelebu, Bukit Panjang, West Region, Singapore, 678972, Singapore"
  },
  "heartbeat@bedok activesg sport centre": {
    "lat": 1.3268941,
    "lng": 103.9320517,
    "display": "Heartbeat@Bedok, Bedok, East Region, Singapore, 469662, Singapore"
  },
  "hillgrove secondary school hall": {
    "lat": 1.3533675,
    "lng": 103.7529905,
    "display": "Hillgrove Secondary School, 10, Bukit Batok Street 52, Guilin, Bukit Batok, West Region, Singapore, 659250, Singapore"
  },
  "hougang primary school hall": {
    "lat": 1.3783581,
    "lng": 103.881072,
    "display": "Hougang Primary School, 1, Hougang Street 93, Trafalgar, Buangkok, Hougang, North-east Region, Singapore, 534238, Singapore"
  },
  "hougang secondary school hall": {
    "lat": 1.3777626,
    "lng": 103.8824589,
    "display": "Hougang Secondary School, 2, Hougang Street 93, Trafalgar, Buangkok, Hougang, North-east Region, Singapore, 534256, Singapore"
  },
  "hua yi secondary school hall": {
    "lat": 1.3520885,
    "lng": 103.7216252,
    "display": "Hua Yi Secondary School, 60, Jurong West Street 42, Hong Kah, Jurong West, West Region, Singapore, 649371, Singapore"
  },
  "innova primary school hall": {
    "lat": 1.4291943,
    "lng": 103.7907449,
    "display": "Innova Primary School, 80, Woodlands Drive 17, Woodlands South, Woodlands, North Region, Singapore, 737888, Singapore"
  },
  "jing shan primary school hall": {
    "lat": 1.3721664,
    "lng": 103.8520081,
    "display": "Jing Shan Primary School, 5, Ang Mo Kio Street 52, Cheng San, Ang Mo Kio, North-east Region, Singapore, 569228, Singapore"
  },
  "junyuan primary school hall": {
    "lat": 1.3477801,
    "lng": 103.9393874,
    "display": "Junyuan Primary School, 2, Tampines Street 91, Tampines West, Tampines, East Region, Singapore, 528906, Singapore"
  },
  "junyuan secondary school hall": {
    "lat": 1.3531753,
    "lng": 103.9335447,
    "display": "Junyuan Secondary School, 11, Tampines Street 84, Tampines West, Tampines, East Region, Singapore, 528933, Singapore"
  },
  "jurong primary school hall": {
    "lat": 1.3487249,
    "lng": 103.7330556,
    "display": "Jurong Primary School, 320, Jurong East Street 32, Yuhua West, Yuhua, Jurong East, West Region, Singapore, 609476, Singapore"
  },
  "jurong secondary school hall": {
    "lat": 1.33031,
    "lng": 103.7239742,
    "display": "Jurong Secondary School, 31, Yuan Ching Road, Taman Jurong, Jurong West, West Region, Singapore, 618652, Singapore"
  },
  "jurongville secondary school hall": {
    "lat": 1.3512965,
    "lng": 103.7289774,
    "display": "Jurongville Secondary School, 202, Jurong East Avenue 1, Yuhua West, Jurong East, West Region, Singapore, 609790, Singapore"
  },
  "kranji primary school hall": {
    "lat": 1.3592308,
    "lng": 103.7283985,
    "display": "Kranji Primary School, Tengah, West Region, Singapore"
  },
  "kranji secondary school hall": {
    "lat": 1.3904766,
    "lng": 103.741139,
    "display": "Kranji Secondary School, 61, Choa Chu Kang Street 51, Choa Chu Kang North, Choa Chu Kang, West Region, Singapore, 689333, Singapore"
  },
  "lakeside primary school hall": {
    "lat": 1.3383897,
    "lng": 103.7179816,
    "display": "Lakeside Primary School, 161, Corporation Walk, Taman Jurong, Jurong West, West Region, Singapore, 618310, Singapore"
  },
  "maha bodhi school hall": {
    "lat": 1.3284777,
    "lng": 103.9015345,
    "display": "Maha Bodhi School, 10, Ubi Avenue 1, Kampong Ubi, Geylang, Central Region, Singapore, 408931, Singapore"
  },
  "marsiling primary school hall": {
    "lat": 1.4341257,
    "lng": 103.77337,
    "display": "Marsiling Primary School, 31, Woodlands Centre Road, Woodlands West, Marsiling, Woodlands, North Region, Singapore, 738927, Singapore"
  },
  "marsiling secondary school hall": {
    "lat": 1.437319,
    "lng": 103.7759431,
    "display": "Marsiling Secondary School, 12, Marsiling Road, Woodlands West, Marsiling, Woodlands, North Region, Singapore, 739110, Singapore"
  },
  "meridian primary school hall": {
    "lat": 1.3760316,
    "lng": 103.9351592,
    "display": "Meridian Primary School, 20, Pasir Ris Street 71, Pasir Ris West, Pasir Ris, East Region, Singapore, 518798, Singapore"
  },
  "meridian secondary school hall": {
    "lat": 1.3675753,
    "lng": 103.9489427,
    "display": "Meridian Secondary School, 31, Pasir Ris Street 51, Pasir Ris Central, Pasir Ris, East Region, Singapore, 518901, Singapore"
  },
  "montfort junior school hall": {
    "lat": 1.3746524,
    "lng": 103.8895368,
    "display": "Montfort Junior School, 52, Hougang Avenue 8, Hougang West, Buangkok, Hougang, North-east Region, Singapore, 538786, Singapore"
  },
  "nan chiau primary school hall": {
    "lat": 1.3920268,
    "lng": 103.8910424,
    "display": "Nan Chiau Primary School, 50, Anchorvale Link, Anchorvale, Sengkang, North-east Region, Singapore, 545080, Singapore"
  },
  "nan chiau high school hall": {
    "lat": 1.3894693,
    "lng": 103.8900833,
    "display": "Nan Chiau High School, 20, Anchorvale Link, Anchorvale, Sengkang, North-east Region, Singapore, 545079, Singapore"
  },
  "naval base primary school hall": {
    "lat": 1.4165467,
    "lng": 103.8384703,
    "display": "Naval Base Primary School, 7, Yishun Avenue 4, Yishun South, Yishun, North Region, Singapore, 769028, Singapore"
  },
  "naval base secondary school hall": {
    "lat": 1.419229,
    "lng": 103.8309871,
    "display": "Naval Base Secondary School, 901, Yishun Ring Road, Khatib, Chencharu, Yishun, North Region, Singapore, 768689, Singapore"
  },
  "ngee ann primary school hall": {
    "lat": 1.3056693,
    "lng": 103.9178772,
    "display": "Ngee Ann Primary School, 344, Marine Terrace, Marine Parade, Central Region, Singapore, 449149, Singapore"
  },
  "north vista primary school hall": {
    "lat": 1.3828948,
    "lng": 103.8959771,
    "display": "North Vista Primary School, 20, Compassvale Link, Compassvale, Sengkang, North-east Region, Singapore, 544974, Singapore"
  },
  "north vista secondary school hall": {
    "lat": 1.3817373,
    "lng": 103.8987395,
    "display": "North Vista Secondary School, 11, Rivervale Link, Rivervale, Sengkang, North-east Region, Singapore, 545081, Singapore"
  },
  "northbrooks secondary school hall": {
    "lat": 1.4212669,
    "lng": 103.8447792,
    "display": "Northbrooks Secondary School, 585, Yishun Ring Road, Yishun East, Yishun, North Region, Singapore, 768692, Singapore"
  },
  "oasis primary school hall": {
    "lat": 1.404653,
    "lng": 103.9109764,
    "display": "Oasis Primary School, 71, Edgefield Plains, Waterway East, Punggol, North-east Region, Singapore, 828716, Singapore"
  },
  "our tampines hub": {
    "lat": 1.3530588,
    "lng": 103.9405998,
    "display": "Our Tampines Hub, 1, Tampines Walk, Tampines West, Tampines, East Region, Singapore, 528523, Singapore"
  },
  "palm view primary school hall": {
    "lat": 1.3840612,
    "lng": 103.8912122,
    "display": "Palm View Primary School, 150, Compassvale Bow, Compassvale, Sengkang, North-east Region, Singapore, 544822, Singapore"
  },
  "pei hwa secondary school hall": {
    "lat": 1.3907596,
    "lng": 103.878184,
    "display": "Pei Hwa Secondary School, 21, Fernvale Link, Fernvale, Sengkang, North-east Region, Singapore, 797702, Singapore"
  },
  "pioneer primary school hall": {
    "lat": 1.3545947,
    "lng": 103.7330174,
    "display": "Pioneer Primary School, 80, Tengah Garden Avenue, Tengah Plantation, Tengah, West Region, Singapore, 699915, Singapore"
  },
  "punggol green primary school hall": {
    "lat": 1.4019593,
    "lng": 103.8985497,
    "display": "Punggol Green Primary School, 98, Punggol Walk, Matilda, Punggol Field West, Punggol, North-east Region, Singapore, 828772, Singapore"
  },
  "punggol primary school hall": {
    "lat": 1.3781312,
    "lng": 103.8947545,
    "display": "Punggol Primary School, 61, Hougang Avenue 8, Hougang East, Hougang, North-east Region, Singapore, 538787, Singapore"
  },
  "punggol secondary school hall": {
    "lat": 1.4023982,
    "lng": 103.9091468,
    "display": "Punggol Secondary School, 51, Edgefield Plains, Waterway East, Punggol Central, Punggol, North-east Region, Singapore, 828870, Singapore"
  },
  "punggol view primary school hall": {
    "lat": 1.4053222,
    "lng": 103.9052658,
    "display": "Punggol View Primary School, 9, Punggol Place, Punggol Town Centre, Punggol Central, Punggol, North-east Region, Singapore, 828845, Singapore"
  },
  "queenstown primary school hall": {
    "lat": 1.2960266,
    "lng": 103.8078385,
    "display": "Queenstown Primary School, 310, Margaret Drive, Dawson, Queenstown, Central Region, Singapore, 149303, Singapore"
  },
  "queensway secondary school hall": {
    "lat": 1.3002856,
    "lng": 103.8020079,
    "display": "Queensway Secondary School, 2A, Margaret Drive, Dawson, Queenstown, Central Region, Singapore, 149295, Singapore"
  },
  "rivervale primary school hall": {
    "lat": 1.3936485,
    "lng": 103.9045321,
    "display": "Rivervale Primary School, 80, Rivervale Drive, Rivervale, Sengkang, North-east Region, Singapore, 545092, Singapore"
  },
  "riverside primary school hall": {
    "lat": 1.4472779,
    "lng": 103.8018321,
    "display": "Riverside Primary School, 110, Woodlands Crescent, Woodlands East, Admiralty, Woodlands, North Region, Singapore, 737803, Singapore"
  },
  "riverside secondary school hall": {
    "lat": 1.440982,
    "lng": 103.7881434,
    "display": "Riverside Secondary School, 3, Woodlands Street 81, Midview, Woodlands North Coast, Woodlands, North Region, Singapore, 738524, Singapore"
  },
  "rosyth school hall": {
    "lat": 1.3728695,
    "lng": 103.8745093,
    "display": "Rosyth School, 21, Serangoon North Avenue 4, Serangoon North, Serangoon, North-east Region, Singapore, 555855, Singapore"
  },
  "sembawang primary school hall": {
    "lat": 1.4452668,
    "lng": 103.8209149,
    "display": "Sembawang Primary School, 10, Sembawang Drive, Sembawang Central, Canberra, Sembawang, North Region, Singapore, 757715, Singapore"
  },
  "sembawang secondary school hall": {
    "lat": 1.4456529,
    "lng": 103.8166628,
    "display": "Sembawang Secondary School, 30, Sembawang Crescent, Sembawang Central, Senoko, Sembawang, North Region, Singapore, 757704, Singapore"
  },
  "sengkang green primary school hall": {
    "lat": 1.3928921,
    "lng": 103.8748431,
    "display": "Sengkang Green Primary School, 15, Fernvale Road, Fernvale, Sengkang, North-east Region, Singapore, 797636, Singapore"
  },
  "senja-cashew community centre": {
    "lat": 1.3816703,
    "lng": 103.7647336,
    "display": "Senja-Cashew Community Centre, 101, Bukit Panjang Road, Saujana, Bukit Panjang, West Region, Singapore, 679910, Singapore"
  },
  "si ling primary school hall": {
    "lat": 1.4327548,
    "lng": 103.7857624,
    "display": "Si Ling Primary School, 61, Woodlands Avenue 1, Woodgrove, Woodlands, North Region, Singapore, 739067, Singapore"
  },
  "si ling secondary school hall": {
    "lat": 1.4453339,
    "lng": 103.775269,
    "display": "Si Ling Secondary School, Marsiling Lane, North Coast, Woodlands North Coast, Woodlands, North Region, Singapore, 730220, Singapore"
  },
  "springdale primary school hall": {
    "lat": 1.3950015,
    "lng": 103.8897759,
    "display": "Springdale Primary School, 71, Anchorvale Link, Anchorvale, Sengkang, North-east Region, Singapore, 544799, Singapore"
  },
  "springfield secondary school hall": {
    "lat": 1.349994,
    "lng": 103.9299857,
    "display": "Springfield Secondary School, 30, Tampines Avenue 8, Tampines West, Tampines, East Region, Singapore, 529593, Singapore"
  },
  "tampines north community centre": {
    "lat": 1.3572829,
    "lng": 103.9466634,
    "display": "Tampines North Community Club, 2, Tampines Street 41, Tampines East, Tampines, East Region, Singapore, 529204, Singapore"
  },
  "tanjong katong primary school hall": {
    "lat": 1.3053243,
    "lng": 103.9004551,
    "display": "Tanjong Katong Primary School, 10, Seraya Road, Katong, Marine Parade, Central Region, Singapore, 437259, Singapore"
  },
  "tanjong katong secondary school hall": {
    "lat": 1.3087439,
    "lng": 103.8972354,
    "display": "Tanjong Katong Secondary School, 130, Haig Road, Katong, Marine Parade, Central Region, Singapore, 438796, Singapore"
  },
  "temasek primary school hall": {
    "lat": 1.3174119,
    "lng": 103.9457663,
    "display": "Temasek Primary School, 501, Bedok South Avenue 3, Bedok South, Bedok, East Region, Singapore, 479239, Singapore"
  },
  "temasek secondary school hall": {
    "lat": 1.3163525,
    "lng": 103.9478003,
    "display": "Temasek Secondary School, 600, Upper East Coast Road, Bayshore, Bedok South, Bedok, East Region, Singapore, 465561, Singapore"
  },
  "townsville primary school hall": {
    "lat": 1.3604365,
    "lng": 103.8540368,
    "display": "Townsville Primary School, 3, Ang Mo Kio Avenue 10, Chong Boon, Ang Mo Kio, North-east Region, Singapore, 569730, Singapore"
  },
  "unity primary school hall": {
    "lat": 1.4027367,
    "lng": 103.7467533,
    "display": "Unity Primary School, 21, Choa Chu Kang Crescent, Yew Tee, Choa Chu Kang, West Region, Singapore, 688268, Singapore"
  },
  "west spring primary school hall": {
    "lat": 1.389523,
    "lng": 103.7662653,
    "display": "West Spring Primary School, 60, Bukit Panjang Ring Road, Saujana, Bukit Panjang, West Region, Singapore, 679946, Singapore"
  },
  "west spring secondary school hall": {
    "lat": 1.3882851,
    "lng": 103.7598736,
    "display": "West Spring Secondary School, 61, Senja Road, Senja, Bukit Panjang, West Region, Singapore, 677737, Singapore"
  },
  "westwood primary school hall": {
    "lat": 1.3474424,
    "lng": 103.700513,
    "display": "Westwood Primary School, 1, Jurong West Street 73, Yunnan, Jurong West, West Region, Singapore, 649188, Singapore"
  },
  "westwood secondary school hall": {
    "lat": 1.3535728,
    "lng": 103.7018025,
    "display": "Westwood Secondary School, 11, Jurong West Street 25, Wenya, Jurong West, West Region, Singapore, 648350, Singapore"
  },
  "white sands primary school hall": {
    "lat": 1.365473,
    "lng": 103.9612546,
    "display": "White Sands Primary School, 2, Pasir Ris Street 11, Pasir Ris Drive, Pasir Ris, East Region, Singapore, 519075, Singapore"
  },
  "woodgrove primary school hall": {
    "lat": 1.4331096,
    "lng": 103.790305,
    "display": "Woodgrove Primary School, 2, Woodlands Drive 14, Woodlands South, Woodlands, North Region, Singapore, 738079, Singapore"
  },
  "woodgrove secondary school hall": {
    "lat": 1.4283319,
    "lng": 103.7965492,
    "display": "Woodgrove Secondary School, 3, Woodlands Avenue 6, Woodlands South, Woodlands, North Region, Singapore, 738990, Singapore"
  },
  "woodlands primary school hall": {
    "lat": 1.4366956,
    "lng": 103.7916902,
    "display": "Woodlands Primary School, 10, Woodlands Drive 50, Midview, Woodlands, North Region, Singapore, 738853, Singapore"
  },
  "woodlands ring primary school hall": {
    "lat": 1.4346654,
    "lng": 103.7978405,
    "display": "Woodlands Ring Primary School, 11, Woodlands Ring Road, Woodlands East, Admiralty, Woodlands, North Region, Singapore, 738240, Singapore"
  },
  "woodlands ring secondary school hall": {
    "lat": 1.436023,
    "lng": 103.8004353,
    "display": "Woodlands Ring Secondary School, 10, Woodlands Ring Road, Woodlands East, Admiralty, Woodlands, North Region, Singapore, 738239, Singapore"
  },
  "xinmin primary school hall": {
    "lat": 1.3714019,
    "lng": 103.8831786,
    "display": "Xinmin Primary School, 9, Hougang Avenue 8, Hougang West, Buangkok, Hougang, North-east Region, Singapore, 538784, Singapore"
  },
  "xinmin secondary school hall": {
    "lat": 1.3725582,
    "lng": 103.8829282,
    "display": "Xinmin Secondary School, 11, Hougang Avenue 8, Hougang West, Buangkok, Hougang, North-east Region, Singapore, 538789, Singapore"
  },
  "yishun primary school hall": {
    "lat": 1.4335987,
    "lng": 103.8338869,
    "display": "Yishun Primary School, 500, Yishun Ring Road, Yishun West, Chong Pang, Yishun, North Region, Singapore, 768679, Singapore"
  },
  "yishun secondary school hall": {
    "lat": 1.4279398,
    "lng": 103.8290283,
    "display": "Yishun Secondary School, 4, Yishun Street 71, Yishun West, Chong Pang, Yishun, North Region, Singapore, 768516, Singapore"
  },
  "yishun town secondary school hall": {
    "lat": 1.4326646,
    "lng": 103.8378851,
    "display": "Yishun Town Secondary School, 6, Yishun Street 21, Northland, Chong Pang, Yishun, North Region, Singapore, 768610, Singapore"
  },
  "yuhua primary school hall": {
    "lat": 1.3428913,
    "lng": 103.74096,
    "display": "Yuhua Primary School, 158, Jurong East Street 24, Yuhua East, Yuhua, Jurong East, West Region, Singapore, 609558, Singapore"
  },
  "yuhua secondary school hall": {
    "lat": 1.3468883,
    "lng": 103.7224251,
    "display": "Yuhua Secondary School, 5, Jurong West Street 41, Hong Kah, Jurong West, West Region, Singapore, 649410, Singapore"
  },
  "zhangde primary school hall": {
    "lat": 1.2842497,
    "lng": 103.8260819,
    "display": "Zhangde Primary School, 51, Jalan Membina, Tiong Bahru Station, Bukit Merah, Central Region, Singapore, 169485, Singapore"
  },
  "zhenghua primary school hall": {
    "lat": 1.3794259,
    "lng": 103.7696661,
    "display": "Zhenghua Primary School, 9, Fajar Road, Fajar, Bukit Panjang, West Region, Singapore, 679002, Singapore"
  },
  "zhenghua secondary school hall": {
    "lat": 1.3895029,
    "lng": 103.7651957,
    "display": "Zhenghua Secondary School, 91, Senja Road, Saujana, Bukit Panjang, West Region, Singapore, 677741, Singapore"
  }
};
