// Auto-generated by build-geocache.js — do not edit
const GEOCACHE = {
  "admiralty primary school hall": {
    "lat": 1.4426347903311,
    "lng": 103.800040119743,
    "display": "11 WOODLANDS CIRCLE ADMIRALTY PRIMARY SCHOOL SINGAPORE 738907"
  },
  "ahmad ibrahim secondary school hall": {
    "lat": 1.43605975368804,
    "lng": 103.829718690077,
    "display": "751 YISHUN AVENUE 7 AHMAD IBRAHIM SECONDARY SCHOOL SINGAPORE 768928"
  },
  "anchor green primary school hall": {
    "lat": 1.39036998654612,
    "lng": 103.887165375933,
    "display": "31 ANCHORVALE DRIVE ANCHOR GREEN PRIMARY SCHOOL SINGAPORE 544969"
  },
  "ang mo kio primary school hall": {
    "lat": 1.36932176584608,
    "lng": 103.839630858752,
    "display": "20 ANG MO KIO AVENUE 3 ANG MO KIO PRIMARY SCHOOL SINGAPORE 569920"
  },
  "angsana primary school hall": {
    "lat": 1.36360590588314,
    "lng": 103.9389409004,
    "display": "51 TAMPINES STREET 61 ANGSANA PRIMARY SCHOOL SINGAPORE 528565"
  },
  "beacon primary school hall": {
    "lat": 1.38394936211823,
    "lng": 103.773632022975,
    "display": "36 BUKIT PANJANG RING ROAD BEACON PRIMARY SCHOOL SINGAPORE 679944"
  },
  "beatty secondary school hall": {
    "lat": 1.341790284928,
    "lng": 103.852280842345,
    "display": "1 TOA PAYOH NORTH BEATTY SECONDARY SCHOOL SINGAPORE 318990"
  },
  "bedok green primary school hall": {
    "lat": 1.32344593287992,
    "lng": 103.937878976352,
    "display": "1 BEDOK SOUTH AVENUE 2 BEDOK GREEN PRIMARY SCHOOL SINGAPORE 469317"
  },
  "bedok south secondary school hall": {
    "lat": 1.32513655159184,
    "lng": 103.950989139261,
    "display": "1 JALAN LANGGAR BEDOK BEDOK SOUTH SECONDARY SCHOOL SINGAPORE 468585"
  },
  "bendemeer primary school hall": {
    "lat": 1.32181250780475,
    "lng": 103.865404167629,
    "display": "91 BENDEMEER ROAD BENDEMEER PRIMARY SCHOOL SINGAPORE 339948"
  },
  "bendemeer secondary school hall": {
    "lat": 1.32461111307996,
    "lng": 103.860970284401,
    "display": "1 SAINT WILFRED ROAD BENDEMEER SECONDARY SCHOOL SINGAPORE 327919"
  },
  "bishan clubhouse": {
    "lat": 1.34948,
    "lng": 103.85075,
    "display": "51 BISHAN STREET 13 BISHAN COMMUNITY CLUB SINGAPORE 579799"
  },
  "bishan sport hall": {
    "lat": 1.35550312686221,
    "lng": 103.85100968145,
    "display": "5 BISHAN STREET 14 BISHAN SPORTS HALL SINGAPORE 579783"
  },
  "blangah rise primary school hall": {
    "lat": 1.27612047924037,
    "lng": 103.808628535239,
    "display": "91 TELOK BLANGAH HEIGHTS BLANGAH RISE PRIMARY SCHOOL SINGAPORE 109100"
  },
  "boon lay secondary school hall": {
    "lat": 1.34272216334333,
    "lng": 103.701891453912,
    "display": "11 JURONG WEST STREET 65 BOON LAY SECONDARY SCHOOL SINGAPORE 648354"
  },
  "bowen secondary school hall": {
    "lat": 1.37035994436209,
    "lng": 103.877659577677,
    "display": "2 LORONG NAPIRI BOWEN SECONDARY SCHOOL SINGAPORE 547529"
  },
  "broadrick secondary school hall": {
    "lat": 1.30705061123433,
    "lng": 103.886917922608,
    "display": "61 DAKOTA CRESCENT BROADRICK SECONDARY SCHOOL SINGAPORE 399935"
  },
  "bukit batok secondary school hall": {
    "lat": 1.34849111079052,
    "lng": 103.74087370482,
    "display": "50 BUKIT BATOK WEST AVENUE 8 BUKIT BATOK SECONDARY SCHOOL SINGAPORE 658962"
  },
  "bukit canberra sport centre": {
    "lat": 1.44826,
    "lng": 103.82276,
    "display": "21 CANBERRA LINK BUKIT CANBERRA SINGAPORE 756973"
  },
  "bukit canberra sport hall": {
    "lat": 1.44826,
    "lng": 103.82276,
    "display": "21 CANBERRA LINK BUKIT CANBERRA SINGAPORE 756973"
  },
  "bukit gombak sport centre": {
    "lat": 1.35975603325519,
    "lng": 103.752285494299,
    "display": "810 BUKIT BATOK WEST AVENUE 5 BUKIT GOMBAK SPORTS CENTRE"
  },
  "bukit gombak sport hall": {
    "lat": 1.35981192280926,
    "lng": 103.75225912773,
    "display": "810 BUKIT BATOK WEST AVENUE 5 BUKIT GOMBAK SPORTS HALL SINGAPORE 659088"
  },
  "bukit merah secondary school hall": {
    "lat": 1.28569283064288,
    "lng": 103.813438929393,
    "display": "10 LENGKOK BAHRU BUKIT MERAH SECONDARY SCHOOL SINGAPORE 159050"
  },
  "bukit panjang government high school hall": {
    "lat": 1.37835,
    "lng": 103.76292,
    "display": "3 CHOA CHU KANG AVENUE 4 BUKIT PANJANG GOVT HIGH SCHOOL SINGAPORE 689811"
  },
  "bukit panjang primary school hall": {
    "lat": 1.37362179302436,
    "lng": 103.769374904025,
    "display": "109 CASHEW ROAD BUKIT PANJANG PRIMARY SCHOOL SINGAPORE 679676"
  },
  "bukit timah primary school hall": {
    "lat": 1.3377498622588,
    "lng": 103.766855344779,
    "display": "111 LORONG KISMIS AFTERSCHOOL @ BUKIT TIMAH PRIMARY SCHOOL"
  },
  "bukit view secondary school hall": {
    "lat": 1.3457330554294,
    "lng": 103.752226593984,
    "display": "16 BUKIT BATOK STREET 21 BUKIT VIEW SECONDARY SCHOOL SINGAPORE 659633"
  },
  "canberra primary school hall": {
    "lat": 1.45125024371543,
    "lng": 103.815858858929,
    "display": "21 ADMIRALTY DRIVE CANBERRA PRIMARY SCHOOL SINGAPORE 757714"
  },
  "canberra secondary school hall": {
    "lat": 1.45319086315972,
    "lng": 103.814203583818,
    "display": "51 SEMBAWANG DRIVE CANBERRA SECONDARY SCHOOL SINGAPORE 757699"
  },
  "canossa catholic primary school hall": {
    "lat": 1.32664424544839,
    "lng": 103.882227964852,
    "display": "1 SALLIM ROAD CANOSSA CATHOLIC PRIMARY SCHOOL SINGAPORE 387621"
  },
  "cantonment primary school hall": {
    "lat": 1.27547252623201,
    "lng": 103.839962631748,
    "display": "1 CANTONMENT CLOSE CANTONMENT PRIMARY SCHOOL SINGAPORE 088256"
  },
  "casuarina primary school hall": {
    "lat": 1.37246063927999,
    "lng": 103.957020286115,
    "display": "30 PASIR RIS STREET 41 CASUARINA PRIMARY SCHOOL SINGAPORE 518935"
  },
  "cedar primary school hall": {
    "lat": 1.33566084356265,
    "lng": 103.87562006259,
    "display": "15 CEDAR AVENUE BIG HEART STUDENT CARE (CEDAR PRIMARY SCHOOL)"
  },
  "changkat changi secondary school hall": {
    "lat": 1.33950630072876,
    "lng": 103.953245525564,
    "display": "23 SIMEI STREET 3 CHANGKAT CHANGI SECONDARY SCHOOL SINGAPORE 529894"
  },
  "changkat primary school hall": {
    "lat": 1.34023163951633,
    "lng": 103.952080114035,
    "display": "11 SIMEI STREET 3 CHANGKAT PRIMARY SCHOOL SINGAPORE 529896"
  },
  "choa chu kang sport centre": {
    "lat": 1.39059559281482,
    "lng": 103.748024129362,
    "display": "1 CHOA CHU KANG STREET 53 CHOA CHU KANG SPORTS CENTRE"
  },
  "choa chu kang sport hall": {
    "lat": 1.38546,
    "lng": 103.74729,
    "display": "1 CHOA CHU KANG STREET 53 CHOA CHU KANG SPORTS HALL SINGAPORE 689236"
  },
  "chongzheng primary school hall": {
    "lat": 1.35061130568554,
    "lng": 103.951317297552,
    "display": "1 TAMPINES STREET 21 BIG HEART STUDENT CARE (CHONGZHENG PRIMARY SCHOOL)"
  },
  "christ church secondary school hall": {
    "lat": 1.42656780901455,
    "lng": 103.793451105242,
    "display": "20 WOODLANDS DRIVE 17 CHRIST CHURCH SECONDARY SCHOOL SINGAPORE 737924"
  },
  "chua chu kang secondary school hall": {
    "lat": 1.38333422637073,
    "lng": 103.75510327583,
    "display": "31 TECK WHYE CRESCENT CHUA CHU KANG SECONDARY SCHOOL SINGAPORE 688848"
  },
  "clementi primary school hall": {
    "lat": 1.31506321827875,
    "lng": 103.763144493687,
    "display": "8 CLEMENTI AVENUE 3 CLEMENTI PRIMARY SCHOOL SINGAPORE 129903"
  },
  "clementi sport centre": {
    "lat": 1.31148,
    "lng": 103.76537,
    "display": "518 CLEMENTI AVENUE 3 CLEMENTI SPORTS HALL SINGAPORE 129907"
  },
  "clementi sport hall": {
    "lat": 1.31148,
    "lng": 103.76537,
    "display": "518 CLEMENTI AVENUE 3 CLEMENTI SPORTS HALL SINGAPORE 129907"
  },
  "clementi town secondary school hall": {
    "lat": 1.31553912945073,
    "lng": 103.762020598524,
    "display": "10 CLEMENTI AVENUE 3 CLEMENTI TOWN SECONDARY SCHOOL SINGAPORE 129904"
  },
  "compassvale primary school hall": {
    "lat": 1.39444529636566,
    "lng": 103.897812229905,
    "display": "21 COMPASSVALE STREET COMPASSVALE PRIMARY SCHOOL SINGAPORE 545091"
  },
  "compassvale secondary school hall": {
    "lat": 1.39614083952009,
    "lng": 103.899847164494,
    "display": "51 COMPASSVALE CRESCENT COMPASSVALE SECONDARY SCHOOL SINGAPORE 545083"
  },
  "concord primary school hall": {
    "lat": 1.38026516111464,
    "lng": 103.736554295636,
    "display": "3 CHOA CHU KANG AVENUE 4 BIG HEART STUDENT CARE (CONCORD PRIMARY SCHOOL)"
  },
  "corporation primary school hall": {
    "lat": 1.35099779872539,
    "lng": 103.707593724342,
    "display": "31 JURONG WEST STREET 24 CORPORATION PRIMARY SCHOOL SINGAPORE 648347"
  },
  "crescent girls' school hall": {
    "lat": 1.28843,
    "lng": 103.80008,
    "display": "357 TANGLIN ROAD CRESCENT GIRLS SCHOOL SINGAPORE 247961"
  },
  "crest secondary school hall": {
    "lat": 1.3431198045076,
    "lng": 103.742628105304,
    "display": "561 JURONG EAST STREET 24 CREST SECONDARY SCHOOL SINGAPORE 609561"
  },
  "damai primary school hall": {
    "lat": 1.33546106800406,
    "lng": 103.921270169613,
    "display": "52 BEDOK RESERVOIR CRESCENT DAMAI PRIMARY SCHOOL SINGAPORE 479226"
  },
  "damai secondary school hall": {
    "lat": 1.33692798510393,
    "lng": 103.927091653438,
    "display": "4800 BEDOK RESERVOIR ROAD DAMAI SECONDARY SCHOOL SINGAPORE 479229"
  },
  "dazhong primary school hall": {
    "lat": 1.3591797447277,
    "lng": 103.74847210784,
    "display": "35 BUKIT BATOK STREET 31 DAZHONG PRIMARY SCHOOL SINGAPORE 659441"
  },
  "delta sport centre": {
    "lat": 1.29008,
    "lng": 103.82266,
    "display": "900 TIONG BAHRU ROAD DELTA SPORTS HALL SINGAPORE 158790"
  },
  "delta sport hall": {
    "lat": 1.29008,
    "lng": 103.82266,
    "display": "900 TIONG BAHRU ROAD DELTA SPORTS HALL SINGAPORE 158790"
  },
  "deyi secondary school hall": {
    "lat": 1.36599702567717,
    "lng": 103.852545772422,
    "display": "1 ANG MO KIO STREET 42 DEYI SECONDARY SCHOOL SINGAPORE 569277"
  },
  "dunman high school hall": {
    "lat": 1.29996216014962,
    "lng": 103.88294155989,
    "display": "10 TANJONG RHU ROAD DUNMAN HIGH SCHOOL SINGAPORE 436895"
  },
  "east spring primary school hall": {
    "lat": 1.35268400746357,
    "lng": 103.961676849165,
    "display": "31 TAMPINES STREET 33 EAST SPRING PRIMARY SCHOOL SINGAPORE 529258"
  },
  "east spring secondary school hall": {
    "lat": 1.35622508992581,
    "lng": 103.960640700298,
    "display": "30 TAMPINES STREET 34 EAST SPRING SECONDARY SCHOOL SINGAPORE 529231"
  },
  "edgefield primary school hall": {
    "lat": 1.40009139510996,
    "lng": 103.907847599114,
    "display": "41 EDGEFIELD PLAINS EDGEFIELD PRIMARY SCHOOL SINGAPORE 828869"
  },
  "edgefield secondary school hall": {
    "lat": 1.40059309981824,
    "lng": 103.902687385465,
    "display": "36 PUNGGOL FIELD EDGEFIELD SECONDARY SCHOOL SINGAPORE 828814"
  },
  "elias park primary school hall": {
    "lat": 1.37505696315817,
    "lng": 103.945289416873,
    "display": "11 PASIR RIS STREET 52 AFTERSCHOOL @ ELIAS PARK PRIMARY SCHOOL"
  },
  "endeavour primary school hall": {
    "lat": 1.45403837499301,
    "lng": 103.817436231731,
    "display": "10 ADMIRALTY LINK ENDEAVOUR PRIMARY SCHOOL SINGAPORE 757521"
  },
  "eunos primary school hall": {
    "lat": 1.324223,
    "lng": 103.904727,
    "display": "95 JALAN EUNOS EUNOS PRIMARY SCHOOL SINGAPORE 419529"
  },
  "evergreen primary school hall": {
    "lat": 1.44415332824735,
    "lng": 103.794577787757,
    "display": "31 WOODLANDS CIRCLE EVERGREEN PRIMARY SCHOOL SINGAPORE 738908"
  },
  "evergreen secondary school hall": {
    "lat": 1.44149131273737,
    "lng": 103.794137756171,
    "display": "11 WOODLANDS STREET 83 EVERGREEN SECONDARY SCHOOL SINGAPORE 738489"
  },
  "fairfield methodist primary school hall": {
    "lat": 1.30100441916733,
    "lng": 103.785455606827,
    "display": "100 DOVER ROAD COMMIT LEARNING SCHOOLHOUSE @ FAIRFIELD METHODIST SCHOOL (PRIMARY)"
  },
  "farrer park primary school hall": {
    "lat": 1.31236867681371,
    "lng": 103.850766402965,
    "display": "2 FARRER PARK ROAD FARRER PARK PRIMARY SCHOOL SINGAPORE 217567"
  },
  "fengshan primary school hall": {
    "lat": 1.32980598760785,
    "lng": 103.931710293058,
    "display": "307 BEDOK NORTH ROAD FENGSHAN PRIMARY SCHOOL SINGAPORE 469680"
  },
  "fuhua primary school hall": {
    "lat": 1.33659726465816,
    "lng": 103.736089481883,
    "display": "65 JURONG EAST STREET 13 AMP-MERCU STUDENT CARE CENTRE @ FUHUA PRIMARY SCHOOL"
  },
  "gan eng seng primary school hall": {
    "lat": 1.28559516494962,
    "lng": 103.815547410064,
    "display": "100 REDHILL CLOSE GAN ENG SENG PRIMARY SCHOOL SINGAPORE 158901"
  },
  "geylang methodist primary school hall": {
    "lat": 1.31759126757284,
    "lng": 103.883845744916,
    "display": "4 GEYLANG EAST CENTRAL GEYLANG METHODIST SCHOOL (PRIMARY) SINGAPORE 389706"
  },
  "geylang methodist secondary school hall": {
    "lat": 1.31764900474601,
    "lng": 103.882661129303,
    "display": "2 GEYLANG EAST CENTRAL GEYLANG METHODIST SCHOOL (SECONDARY) SINGAPORE 389705"
  },
  "gongshang primary school hall": {
    "lat": 1.35711606790292,
    "lng": 103.949144797277,
    "display": "1 TAMPINES STREET 42 COMMIT LEARNING SCHOOLHOUSE @ GONGSHANG PRIMARY SCHOOL"
  },
  "greendale primary school hall": {
    "lat": 1.39648195114256,
    "lng": 103.91233462071,
    "display": "50 EDGEDALE PLAINS GREENDALE PRIMARY SCHOOL SINGAPORE 828848"
  },
  "greendale secondary school hall": {
    "lat": 1.39696019936894,
    "lng": 103.91170014084,
    "display": "51 EDGEDALE PLAINS GREENDALE SECONDARY SCHOOL SINGAPORE 828866"
  },
  "greenridge primary school hall": {
    "lat": 1.3858892193692,
    "lng": 103.767794469258,
    "display": "11 JELAPANG ROAD GREENRIDGE PRIMARY SCHOOL SINGAPORE 677744"
  },
  "greenridge secondary school hall": {
    "lat": 1.375600053443,
    "lng": 103.763998914082,
    "display": "31 GANGSA ROAD GREENRIDGE SECONDARY SCHOOL SINGAPORE 678972"
  },
  "heartbeat@bedok activesg sport centre": {
    "lat": 1.32704197090859,
    "lng": 103.932394011989,
    "display": "11 BEDOK NORTH STREET 1 HEARTBEAT @ BEDOK ACTIVESG SPORT CENTRE"
  },
  "hillgrove secondary school hall": {
    "lat": 1.35273576615912,
    "lng": 103.752986488399,
    "display": "10 BUKIT BATOK STREET 52 HILLGROVE SECONDARY SCHOOL SINGAPORE 659250"
  },
  "hong kah secondary school hall": {
    "lat": 1.35166667056342,
    "lng": 103.727083852629,
    "display": "931 JURONG WEST STREET 42 HONG KAH SECONDARY SCHOOL"
  },
  "hougang primary school hall": {
    "lat": 1.37738245231461,
    "lng": 103.880805274557,
    "display": "1 HOUGANG STREET 93 HOUGANG PRIMARY SCHOOL SINGAPORE 534238"
  },
  "hougang secondary school hall": {
    "lat": 1.37764019332164,
    "lng": 103.882533963338,
    "display": "2 HOUGANG STREET 93 HOUGANG SECONDARY SCHOOL SINGAPORE 534256"
  },
  "hougang sport centre": {
    "lat": 1.3704490003523,
    "lng": 103.888075069741,
    "display": "93 HOUGANG AVENUE 4 HOUGANG SPORTS CENTRE"
  },
  "hougang sport hall": {
    "lat": 1.37057364188039,
    "lng": 103.888071729132,
    "display": "93 HOUGANG AVENUE 4 HOUGANG SPORTS HALL SINGAPORE 538832"
  },
  "hua yi secondary school hall": {
    "lat": 1.35234365488339,
    "lng": 103.721832320169,
    "display": "60 JURONG WEST STREET 42 HUA YI SECONDARY SCHOOL SINGAPORE 649371"
  },
  "innova primary school hall": {
    "lat": 1.42896700684852,
    "lng": 103.790607539185,
    "display": "80 WOODLANDS DRIVE 17 INNOVA PRIMARY SCHOOL SINGAPORE 737888"
  },
  "jalan besar sport centre": {
    "lat": 1.30952190174503,
    "lng": 103.860211336261,
    "display": "100 TYRWHITT ROAD JALAN BESAR SPORTS CENTRE"
  },
  "jalan besar sport hall": {
    "lat": 1.30952190174503,
    "lng": 103.860211336261,
    "display": "100 TYRWHITT ROAD JALAN BESAR SPORTS CENTRE"
  },
  "jing shan primary school hall": {
    "lat": 1.37223290983498,
    "lng": 103.852132214306,
    "display": "5 ANG MO KIO STREET 52 JING SHAN PRIMARY SCHOOL SINGAPORE 569228"
  },
  "junyuan primary school hall": {
    "lat": 1.34787074766746,
    "lng": 103.939221709073,
    "display": "2 TAMPINES STREET 91 JUNYUAN PRIMARY SCHOOL SINGAPORE 528906"
  },
  "junyuan secondary school hall": {
    "lat": 1.35361315263537,
    "lng": 103.933886165824,
    "display": "11 TAMPINES STREET 84 JUNYUAN SECONDARY SCHOOL SINGAPORE 528933"
  },
  "jurong east sport centre": {
    "lat": 1.34678602803049,
    "lng": 103.729259406684,
    "display": "21 JURONG EAST STREET 31 JURONG EAST SPORTS & RECREATION CENTRE SINGAPORE 609517"
  },
  "jurong east sport hall": {
    "lat": 1.34679361539209,
    "lng": 103.729228629547,
    "display": "21 JURONG EAST STREET 31 JURONG EAST SPORTS HALL"
  },
  "jurong primary school hall": {
    "lat": 1.34843859698946,
    "lng": 103.733156566858,
    "display": "320 JURONG EAST STREET 32 JURONG PRIMARY SCHOOL SINGAPORE 609476"
  },
  "jurong secondary school hall": {
    "lat": 1.33002032220942,
    "lng": 103.723952961648,
    "display": "31 YUAN CHING ROAD JURONG SECONDARY SCHOOL SINGAPORE 618652"
  },
  "jurong west sport centre": {
    "lat": 1.33823750104445,
    "lng": 103.693854311183,
    "display": "20 JURONG WEST STREET 93 JURONG WEST SPORTS CENTRE"
  },
  "jurong west sport hall": {
    "lat": 1.33841807201419,
    "lng": 103.693768895177,
    "display": "20 JURONG WEST STREET 93 JURONG WEST SPORTS HALL"
  },
  "jurongville secondary school hall": {
    "lat": 1.35128862770284,
    "lng": 103.728907710089,
    "display": "202 JURONG EAST AVENUE 1 JURONGVILLE SECONDARY SCHOOL SINGAPORE 609790"
  },
  "kallang sport centre": {
    "lat": 1.30435821251939,
    "lng": 103.869935831599,
    "display": "10 STADIUM LANE KALLANG WATER SPORT CENTRE SINGAPORE 397774"
  },
  "kallang sport hall": {
    "lat": 1.30435821251939,
    "lng": 103.869935831599,
    "display": "10 STADIUM LANE KALLANG WATER SPORT CENTRE SINGAPORE 397774"
  },
  "kranji primary school hall": {
    "lat": 1.39356050497104,
    "lng": 103.747362720939,
    "display": "11 CHOA CHU KANG STREET 54 KRANJI PRIMARY SCHOOL SINGAPORE 689189"
  },
  "kranji secondary school hall": {
    "lat": 1.39005109871311,
    "lng": 103.741190664845,
    "display": "61 CHOA CHU KANG STREET 51 KRANJI SECONDARY SCHOOL SINGAPORE 689333"
  },
  "lakeside primary school hall": {
    "lat": 1.33820397704287,
    "lng": 103.718089546664,
    "display": "161 CORPORATION WALK LAKESIDE PRIMARY SCHOOL SINGAPORE 618310"
  },
  "lianhua primary school hall": {
    "lat": 1.35424191127295,
    "lng": 103.754165828711,
    "display": "2 BUKIT BATOK STREET 52 LIANHUA PRIMARY SCHOOL SINGAPORE 659243"
  },
  "maha bodhi school hall": {
    "lat": 1.32858023873554,
    "lng": 103.901306904157,
    "display": "10 UBI AVENUE 1 AFTER SCHOOL @ MAHA BODHI SCHOOL"
  },
  "marsiling primary school hall": {
    "lat": 1.43383904037059,
    "lng": 103.773643013846,
    "display": "31 WOODLANDS CENTRE ROAD MARSILING PRIMARY SCHOOL SINGAPORE 738927"
  },
  "marsiling secondary school hall": {
    "lat": 1.43664424769955,
    "lng": 103.776008090454,
    "display": "12 MARSILING ROAD MARSILING SECONDARY SCHOOL SINGAPORE 739110"
  },
  "meridian primary school hall": {
    "lat": 1.37552831658484,
    "lng": 103.934889078518,
    "display": "20 PASIR RIS STREET 71 MERIDIAN PRIMARY SCHOOL SINGAPORE 518798"
  },
  "meridian secondary school hall": {
    "lat": 1.3672468492013,
    "lng": 103.948972483629,
    "display": "31 PASIR RIS STREET 51 MERIDIAN SECONDARY SCHOOL SINGAPORE 518901"
  },
  "montfort junior school hall": {
    "lat": 1.37362445234082,
    "lng": 103.889741457901,
    "display": "52 HOUGANG AVENUE 8 LEARNING STUDIO EDUCARE BY ZENITANT (MONTFORT JUNIOR SCHOOL)"
  },
  "montfort secondary school hall": {
    "lat": 1.37396131656912,
    "lng": 103.888928372577,
    "display": "50 HOUGANG AVENUE 8 MONTFORT SECONDARY SCHOOL SINGAPORE 538785"
  },
  "nan chiau primary school hall": {
    "lat": 1.39221149906592,
    "lng": 103.891180928186,
    "display": "50 ANCHORVALE LINK NAN CHIAU PRIMARY SCHOOL SINGAPORE 545080"
  },
  "nan chiau high school hall": {
    "lat": 1.38879582498399,
    "lng": 103.890004423764,
    "display": "20 ANCHORVALE LINK NAN CHIAU HIGH SCHOOL SINGAPORE 545079"
  },
  "naval base primary school hall": {
    "lat": 1.41630663159387,
    "lng": 103.838794077233,
    "display": "7 YISHUN AVENUE 4 NAVAL BASE PRIMARY SCHOOL SINGAPORE 769028"
  },
  "naval base secondary school hall": {
    "lat": 1.41937881620441,
    "lng": 103.831050390247,
    "display": "901 YISHUN RING ROAD NAVAL BASE SECONDARY SCHOOL SINGAPORE 768689"
  },
  "new town primary school hall": {
    "lat": 1.29964188181021,
    "lng": 103.80010216304,
    "display": "300 TANGLIN HALT ROAD NEW TOWN PRIMARY SCHOOL SINGAPORE 148812"
  },
  "ngee ann primary school hall": {
    "lat": 1.30552505910497,
    "lng": 103.917463017497,
    "display": "344 MARINE TERRACE NGEE ANN PRIMARY SCHOOL SINGAPORE 449149"
  },
  "north vista primary school hall": {
    "lat": 1.38282243016299,
    "lng": 103.895961877928,
    "display": "20 COMPASSVALE LINK NORTH VISTA PRIMARY SCHOOL SINGAPORE 544974"
  },
  "north vista secondary school hall": {
    "lat": 1.381131285358,
    "lng": 103.899188813886,
    "display": "11 RIVERVALE LINK NORTH VISTA SECONDARY SCHOOL SINGAPORE 545081"
  },
  "northbrooks secondary school hall": {
    "lat": 1.42081285020652,
    "lng": 103.845147332528,
    "display": "585 YISHUN RING ROAD NORTHBROOKS SECONDARY SCHOOL SINGAPORE 768692"
  },
  "oasis primary school hall": {
    "lat": 1.40462413200793,
    "lng": 103.911120600638,
    "display": "71 EDGEFIELD PLAINS OASIS PRIMARY SCHOOL SINGAPORE 828716"
  },
  "our tampines hub": {
    "lat": 1.35354740485205,
    "lng": 103.940381104547,
    "display": "1 TAMPINES WALK HAWKER CENTRE @ OUR TAMPINES HUB"
  },
  "palm view primary school hall": {
    "lat": 1.38376923022123,
    "lng": 103.891354675017,
    "display": "150 COMPASSVALE BOW PALM VIEW PRIMARY SCHOOL SINGAPORE 544822"
  },
  "pasir ris sport centre": {
    "lat": 1.37443844465036,
    "lng": 103.95195282292,
    "display": "120 PASIR RIS CENTRAL PASIR RIS SPORTS CENTRE"
  },
  "pasir ris sport hall": {
    "lat": 1.37405935580675,
    "lng": 103.951850332313,
    "display": "120 PASIR RIS CENTRAL PASIR RIS SPORTS AND RECREATION CENTRE SINGAPORE 519640"
  },
  "paya lebar methodist girls school hall": {
    "lat": 1.3502545600894,
    "lng": 103.884846876112,
    "display": "298 LORONG AH SOO COMMIT LEARNING SCHOOLHOUSE @ PAYA LEBAR METHODIST GIRLS' SCHOOL"
  },
  "pei hwa secondary school hall": {
    "lat": 1.39037504993234,
    "lng": 103.878461745339,
    "display": "21 FERNVALE LINK PEI HWA SECONDARY SCHOOL SINGAPORE 797702"
  },
  "pioneer primary school hall": {
    "lat": 1.35442592930738,
    "lng": 103.732790920197,
    "display": "80 TENGAH GARDEN AVENUE PIONEER PRIMARY SCHOOL SINGAPORE 699915"
  },
  "punggol green primary school hall": {
    "lat": 1.40172590450528,
    "lng": 103.898794262307,
    "display": "98 PUNGGOL WALK LEARNING LEAP PTE LTD (PUNGGOL GREEN PRIMARY SCHOOL)"
  },
  "punggol primary school hall": {
    "lat": 1.37820062547641,
    "lng": 103.894667159512,
    "display": "61 HOUGANG AVENUE 8 AFTERSCHOOL @ PUNGGOL PRIMARY SCHOOL"
  },
  "punggol secondary school hall": {
    "lat": 1.40205738421399,
    "lng": 103.909213706482,
    "display": "51 EDGEFIELD PLAINS PUNGGOL SECONDARY SCHOOL SINGAPORE 828870"
  },
  "punggol view primary school hall": {
    "lat": 1.40514582647962,
    "lng": 103.905156371376,
    "display": "9 PUNGGOL PLACE PUNGGOL VIEW PRIMARY SCHOOL SINGAPORE 828845"
  },
  "queenstown primary school hall": {
    "lat": 1.29559365009015,
    "lng": 103.807548617332,
    "display": "310 MARGARET DRIVE QUEENSTOWN PRIMARY SCHOOL SINGAPORE 149303"
  },
  "queenstown sport centre": {
    "lat": 1.29672719982417,
    "lng": 103.802435206972,
    "display": "473 STIRLING ROAD QUEENSTOWN SPORTS CENTRE"
  },
  "queenstown sport hall": {
    "lat": 1.29672719982417,
    "lng": 103.802435206972,
    "display": "473 STIRLING ROAD QUEENSTOWN SPORTS CENTRE"
  },
  "queensway secondary school hall": {
    "lat": 1.30022271592188,
    "lng": 103.802207291625,
    "display": "2A MARGARET DRIVE QUEENSWAY SECONDARY SCHOOL SINGAPORE 149295"
  },
  "rivervale primary school hall": {
    "lat": 1.39340997767762,
    "lng": 103.904559511997,
    "display": "80 RIVERVALE DRIVE RIVERVALE PRIMARY SCHOOL SINGAPORE 545092"
  },
  "riverside primary school hall": {
    "lat": 1.44700426493785,
    "lng": 103.801889031334,
    "display": "110 WOODLANDS CRESCENT MERCU STUDENT CARE CENTRE @ RIVERSIDE PRIMARY SCHOOL"
  },
  "riverside secondary school hall": {
    "lat": 1.44110157139127,
    "lng": 103.78830823641,
    "display": "3 WOODLANDS STREET 81 RIVERSIDE SECONDARY SCHOOL SINGAPORE 738524"
  },
  "rosyth school hall": {
    "lat": 1.37289067499064,
    "lng": 103.875001549174,
    "display": "21 SERANGOON NORTH AVENUE 4 ROSYTH SCHOOL SINGAPORE 555855"
  },
  "sembawang primary school hall": {
    "lat": 1.44504676205659,
    "lng": 103.82102212387,
    "display": "10 SEMBAWANG DRIVE SEMBAWANG PRIMARY SCHOOL SINGAPORE 757715"
  },
  "sembawang secondary school hall": {
    "lat": 1.44531502131387,
    "lng": 103.816843258118,
    "display": "30 SEMBAWANG CRESCENT SEMBAWANG SECONDARY SCHOOL SINGAPORE 757704"
  },
  "sengkang green primary school hall": {
    "lat": 1.39284606680477,
    "lng": 103.875217666486,
    "display": "15 FERNVALE ROAD SENGKANG GREEN PRIMARY SCHOOL SINGAPORE 797636"
  },
  "sengkang sport centre": {
    "lat": 1.39652429146111,
    "lng": 103.887101924883,
    "display": "57 ANCHORVALE ROAD SENGKANG SPORTS CENTRE"
  },
  "sengkang sport hall": {
    "lat": 1.39652429146111,
    "lng": 103.887101924883,
    "display": "57 ANCHORVALE ROAD SENGKANG SPORTS CENTRE"
  },
  "senja-cashew community centre": {
    "lat": 1.3816381331934,
    "lng": 103.764676250968,
    "display": "101 BUKIT PANJANG ROAD SENJA-CASHEW COMMUNITY CLUB SINGAPORE 679910"
  },
  "si ling primary school hall": {
    "lat": 1.43240935732525,
    "lng": 103.786035065192,
    "display": "61 WOODLANDS AVENUE 1 SI LING PRIMARY SCHOOL SINGAPORE 739067"
  },
  "si ling secondary school hall": {
    "lat": 1.43254,
    "lng": 103.77407,
    "display": "11 MARSILING LANE SI LING SECONDARY SCHOOL SINGAPORE 739148"
  },
  "springdale primary school hall": {
    "lat": 1.39467010299293,
    "lng": 103.889926221247,
    "display": "71 ANCHORVALE LINK SPRINGDALE PRIMARY SCHOOL SINGAPORE 544799"
  },
  "springfield secondary school hall": {
    "lat": 1.34957303471476,
    "lng": 103.930354460693,
    "display": "30 TAMPINES AVENUE 8 SPRINGFIELD SECONDARY SCHOOL SINGAPORE 529593"
  },
  "tampines north community centre": {
    "lat": 1.35736479273941,
    "lng": 103.946602676162,
    "display": "2 TAMPINES STREET 41 TAMPINES NORTH COMMUNITY CLUB SINGAPORE 529204"
  },
  "tampines sport centre": {
    "lat": 1.3538120070574,
    "lng": 103.939790591016,
    "display": "1 TAMPINES WALK TAMPINES SPORTS CENTRE"
  },
  "tampines sport hall": {
    "lat": 1.34289783459176,
    "lng": 103.933398398491,
    "display": "21 TAMPINES AVENUE 1 TEMASEK POLYTECHNIC (29 SPORT COMPLEX) SINGAPORE 529757"
  },
  "tanjong katong primary school hall": {
    "lat": 1.30498489044822,
    "lng": 103.899999965407,
    "display": "10 SERAYA ROAD AFTERSCHOOL @ TANJONG KATONG PRIMARY SCHOOL"
  },
  "tanjong katong secondary school hall": {
    "lat": 1.30873515955341,
    "lng": 103.897225196199,
    "display": "130 HAIG ROAD TANJONG KATONG SECONDARY SCHOOL SINGAPORE 438796"
  },
  "temasek primary school hall": {
    "lat": 1.31770677551333,
    "lng": 103.945590669163,
    "display": "501 BEDOK SOUTH AVENUE 3 TEMASEK PRIMARY SCHOOL SINGAPORE 469300"
  },
  "temasek secondary school hall": {
    "lat": 1.31591673150616,
    "lng": 103.947564112022,
    "display": "600 UPPER EAST COAST ROAD TEMASEK SECONDARY SCHOOL SINGAPORE 465561"
  },
  "toa payoh sport centre": {
    "lat": 1.3306,
    "lng": 103.84999,
    "display": "301 LORONG 6 TOA PAYOH SINGAPORE 319392"
  },
  "toa payoh sport hall": {
    "lat": 1.3306,
    "lng": 103.84999,
    "display": "301 LORONG 6 TOA PAYOH SINGAPORE 319392"
  },
  "townsville primary school hall": {
    "lat": 1.36003263746623,
    "lng": 103.853826048327,
    "display": "3 ANG MO KIO AVENUE 10 TOWNSVILLE PRIMARY SCHOOL SINGAPORE 569730"
  },
  "unity primary school hall": {
    "lat": 1.40285481877246,
    "lng": 103.746822625758,
    "display": "21 CHOA CHU KANG CRESCENT UNITY PRIMARY SCHOOL SINGAPORE 688268"
  },
  "west spring primary school hall": {
    "lat": 1.38944145898943,
    "lng": 103.766195711835,
    "display": "60 BUKIT PANJANG RING ROAD WEST SPRING PRIMARY SCHOOL SINGAPORE 679946"
  },
  "west spring secondary school hall": {
    "lat": 1.38782283303782,
    "lng": 103.760128840155,
    "display": "61 SENJA ROAD WEST SPRING SECONDARY SCHOOL SINGAPORE 677737"
  },
  "westwood primary school hall": {
    "lat": 1.34718456606375,
    "lng": 103.70053420978,
    "display": "1 JURONG WEST STREET 73 WESTWOOD PRIMARY SCHOOL SINGAPORE 649188"
  },
  "westwood secondary school hall": {
    "lat": 1.35373698510994,
    "lng": 103.701772102139,
    "display": "11 JURONG WEST STREET 25 WESTWOOD SECONDARY SCHOOL SINGAPORE 648350"
  },
  "white sands primary school hall": {
    "lat": 1.36563610941695,
    "lng": 103.960861814678,
    "display": "2 PASIR RIS STREET 11 LEARNING LEAP PTE LTD (WHITE SANDS PRIMARY SCHOOL)"
  },
  "woodgrove primary school hall": {
    "lat": 1.43273620725049,
    "lng": 103.79023031392,
    "display": "2 WOODLANDS DRIVE 14 COMMIT LEARNING SCHOOLHOUSE @ WOODGROVE PRIMARY SCHOOL"
  },
  "woodgrove secondary school hall": {
    "lat": 1.42831828137013,
    "lng": 103.79604758539,
    "display": "3 WOODLANDS AVENUE 6 WOODGROVE SECONDARY SCHOOL SINGAPORE 738990"
  },
  "woodlands primary school hall": {
    "lat": 1.43658270720199,
    "lng": 103.791791282236,
    "display": "10 WOODLANDS DRIVE 50 COMMIT LEARNING SCHOOLHOUSE @ WOODLANDS PRIMARY SCHOOL"
  },
  "woodlands ring primary school hall": {
    "lat": 1.43495229315857,
    "lng": 103.797435733144,
    "display": "11 WOODLANDS RING ROAD WOODLANDS RING PRIMARY SCHOOL SINGAPORE 738240"
  },
  "woodlands ring secondary school hall": {
    "lat": 1.43070452883799,
    "lng": 103.777625748539,
    "display": "21 WOODLANDS AVENUE 1 WOODLANDS RING SECONDARY SCHOOL (TILL JAN 2029) SINGAPORE 739062"
  },
  "woodlands sport centre": {
    "lat": 1.4350799762723,
    "lng": 103.780505107227,
    "display": "1 WOODLANDS STREET 13 WOODLANDS SPORTS CENTRE"
  },
  "woodlands sport hall": {
    "lat": 1.4341397536544,
    "lng": 103.77985009679,
    "display": "2 WOODLANDS STREET 12 WOODLANDS SPORTS HALL SINGAPORE 738620"
  },
  "xinmin primary school hall": {
    "lat": 1.37139548941931,
    "lng": 103.883080767491,
    "display": "9 HOUGANG AVENUE 8 XINMIN PRIMARY SCHOOL SINGAPORE 538784"
  },
  "xinmin secondary school hall": {
    "lat": 1.37255884700002,
    "lng": 103.88305161385,
    "display": "11 HOUGANG AVENUE 8 XINMIN SECONDARY SCHOOL SINGAPORE 538789"
  },
  "yio chu kang sport centre": {
    "lat": 1.38227243947685,
    "lng": 103.845767848209,
    "display": "200 ANG MO KIO AVENUE 9 YIO CHU KANG SPORTS CENTRE"
  },
  "yio chu kang sport hall": {
    "lat": 1.38362584863622,
    "lng": 103.845867076799,
    "display": "214 ANG MO KIO AVENUE 9 YIO CHU KANG SPORTS HALL SINGAPORE 569780"
  },
  "yishun primary school hall": {
    "lat": 1.43338602975674,
    "lng": 103.834087115915,
    "display": "500 YISHUN RING ROAD YISHUN PRIMARY SCHOOL SINGAPORE 768679"
  },
  "yishun secondary school hall": {
    "lat": 1.42813324276086,
    "lng": 103.828764316679,
    "display": "4 YISHUN STREET 71 YISHUN SECONDARY SCHOOL SINGAPORE 768516"
  },
  "yishun sport centre": {
    "lat": 1.42415525542106,
    "lng": 103.8409701987,
    "display": "60 YISHUN AVENUE 4 SAFRA ADVENTURE SPORT CENTRE"
  },
  "yishun sport hall": {
    "lat": 1.4117869196196,
    "lng": 103.831215898536,
    "display": "101 YISHUN AVENUE 1 YISHUN SPORTS HALL SINGAPORE 769130"
  },
  "yishun town secondary school hall": {
    "lat": 1.43232156717386,
    "lng": 103.838094226361,
    "display": "6 YISHUN STREET 21 YISHUN TOWN SECONDARY SCHOOL SINGAPORE 768610"
  },
  "yuhua primary school hall": {
    "lat": 1.34280230475033,
    "lng": 103.741105772644,
    "display": "158 JURONG EAST STREET 24 YUHUA PRIMARY SCHOOL SINGAPORE 609558"
  },
  "yuhua secondary school hall": {
    "lat": 1.34718626876968,
    "lng": 103.722687235839,
    "display": "35 JURONG WEST STREET 41 YUHUA SECONDARY SCHOOL SINGAPORE 649406"
  },
  "zhangde primary school hall": {
    "lat": 1.28421153335379,
    "lng": 103.825951875662,
    "display": "51 JALAN MEMBINA ZHANGDE PRIMARY SCHOOL SINGAPORE 169485"
  },
  "zhenghua primary school hall": {
    "lat": 1.37954887512229,
    "lng": 103.769313521752,
    "display": "9 FAJAR ROAD ZHENGHUA PRIMARY SCHOOL SINGAPORE 679002"
  },
  "zhenghua secondary school hall": {
    "lat": 1.38836583415352,
    "lng": 103.765510638527,
    "display": "62 BUKIT PANJANG RING ROAD ZHENGHUA SECONDARY SCHOOL SINGAPORE 679962"
  }
};
