// Canonical list of bookable ActiveSG badminton venue names.
//
// Single source of truth: build-geocache.js (cache generation) and
// validate.js (drift checks) both import this list, so the names can no
// longer drift out of sync between the geocode cache and the build script.
//
// When ActiveSG adds or renames a venue, edit this list, then rerun
// `node build-geocache.js` and `node validate.js`.

const VENUE_NAMES = [
  "Admiralty Primary School Hall",
  "Ahmad Ibrahim Secondary School Hall",
  "Anchor Green Primary School Hall",
  "Ang Mo Kio Primary School Hall",
  "Angsana Primary School Hall",
  "Beacon Primary School Hall",
  "Beatty Secondary School Hall",
  "Bedok Green Primary School Hall",
  "Bedok South Secondary School Hall",
  "Bendemeer Primary School Hall",
  "Bendemeer Secondary School Hall",
  "Bishan Clubhouse",
  "Bishan Sport Hall",
  "Blangah Rise Primary School Hall",
  "Boon Lay Secondary School Hall",
  "Bowen Secondary School Hall",
  "Broadrick Secondary School Hall",
  "Bukit Batok Secondary School Hall",
  "Bukit Canberra Sport Centre",
  "Bukit Canberra Sport Hall",
  "Bukit Gombak Sport Centre",
  "Bukit Gombak Sport Hall",
  "Bukit Merah Secondary School Hall",
  "Bukit Panjang Government High School Hall",
  "Bukit Panjang Primary School Hall",
  "Bukit Timah Primary School Hall",
  "Bukit View Secondary School Hall",
  "Canberra Primary School Hall",
  "Canberra Secondary School Hall",
  "Canossa Catholic Primary School Hall",
  "Cantonment Primary School Hall",
  "Casuarina Primary School Hall",
  "Cedar Primary School Hall",
  "Changkat Changi Secondary School Hall",
  "Changkat Primary School Hall",
  "Choa Chu Kang Sport Centre",
  "Choa Chu Kang Sport Hall",
  "Chongzheng Primary School Hall",
  "Christ Church Secondary School Hall",
  "Chua Chu Kang Secondary School Hall",
  "Clementi Primary School Hall",
  "Clementi Sport Centre",
  "Clementi Sport Hall",
  "Clementi Town Secondary School Hall",
  "Compassvale Primary School Hall",
  "Compassvale Secondary School Hall",
  "Concord Primary School Hall",
  "Corporation Primary School Hall",
  "Crescent Girls' School Hall",
  "Crest Secondary School Hall",
  "Damai Primary School Hall",
  "Damai Secondary School Hall",
  "Dazhong Primary School Hall",
  "Delta Sport Centre",
  "Delta Sport Hall",
  "Deyi Secondary School Hall",
  "Dunman High School Hall",
  "East Spring Primary School Hall",
  "East Spring Secondary School Hall",
  "Edgefield Primary School Hall",
  "Edgefield Secondary School Hall",
  "Elias Park Primary School Hall",
  "Endeavour Primary School Hall",
  "Eunos Primary School Hall",
  "Evergreen Primary School Hall",
  "Evergreen Secondary School Hall",
  "Fairfield Methodist Primary School Hall",
  "Farrer Park Primary School Hall",
  "Fengshan Primary School Hall",
  "Fern Green Primary School Hall",
  "First Toa Payoh Primary School Hall",
  "Frontier Primary School Hall",
  "Fuhua Primary School Hall",
  "Fuhua Secondary School Hall",
  "Gan Eng Seng Primary School Hall",
  "Geylang Methodist Primary School Hall",
  "Geylang Methodist Secondary School Hall",
  "Gongshang Primary School Hall",
  "Greendale Primary School Hall",
  "Greendale Secondary School Hall",
  "Greenridge Primary School Hall",
  "Greenridge Secondary School Hall",
  "Greenwood Primary School Hall",
  "Heartbeat @ Bedok ActiveSG Sport Hall",
  "Heartbeat@Bedok ActiveSG Sport Centre",
  "Henry Park Primary School Hall",
  "Hillgrove Secondary School Hall",
  "Hong Kah Secondary School Hall",
  "Hougang Primary School Hall",
  "Hougang Secondary School Hall",
  "Hougang Sport Centre",
  "Hougang Sport Hall",
  "Hua Yi Secondary School Hall",
  "Innova Primary School Hall",
  "Jalan Besar Sport Centre",
  "Jalan Besar Sport Hall",
  "Jiemin Primary School Hall",
  "Jing Shan Primary School Hall",
  "Junyuan Primary School Hall",
  "Junyuan Secondary School Hall",
  "Jurong East Sport Centre",
  "Jurong East Sport Hall",
  "Jurong Primary School Hall",
  "Jurong Secondary School Hall",
  "Jurong West Sport Centre",
  "Jurong West Sport Hall",
  "Jurongville Secondary School Hall",
  "Kallang Sport Centre",
  "Kallang Sport Hall",
  "Kranji Primary School Hall",
  "Kranji Secondary School Hall",
  "Lakeside Primary School Hall",
  "Lianhua Primary School Hall",
  "Maha Bodhi School Hall",
  "Marsiling Primary School Hall",
  "Marsiling Secondary School Hall",
  "Mayflower Secondary School Hall",
  "Meridian Primary School Hall",
  "Meridian Secondary School Hall",
  "MOE (Evans) Sport Hall",
  "Montfort Junior School Hall",
  "Montfort Secondary School Hall",
  "Nan Chiau Primary School Hall",
  "Nan Chiau High School Hall",
  "Naval Base Primary School Hall",
  "Naval Base Secondary School Hall",
  "New Town Primary School Hall",
  "New Town Secondary School Hall",
  "Ngee Ann Primary School Hall",
  "North View Primary School Hall",
  "North Vista Primary School Hall",
  "North Vista Secondary School Hall",
  "Northbrooks Secondary School Hall",
  "Northland Primary School Hall",
  "Northland Secondary School Hall",
  "Northoaks Primary School Hall",
  "Oasis Primary School Hall",
  "Our Tampines Hub",
  "Our Tampines Hub - Community Auditorium",
  "Palm View Primary School Hall",
  "Park View Primary School Hall",
  "Pasir Ris Crest Secondary School Hall",
  "Pasir Ris Secondary School Hall",
  "Pasir Ris Sport Centre",
  "Pasir Ris Sport Hall",
  "Paya Lebar Methodist Girls School Hall",
  "Pei Hwa Secondary School Hall",
  "Peicai Secondary School Hall",
  "Peirce Secondary School Hall",
  "Peiying Primary School Hall",
  "Pioneer Primary School Hall",
  "Poi Ching School Hall",
  "Punggol Green Primary School Hall",
  "Punggol Primary School Hall",
  "Punggol Secondary School Hall",
  "Punggol View Primary School Hall",
  "Qifa Primary School Hall",
  "Qihua Primary School Hall",
  "Queenstown Primary School Hall",
  "Queenstown Sport Centre",
  "Queenstown Sport Hall",
  "Queensway Secondary School Hall",
  "Radin Mas Primary School Hall",
  "Red Swastika School Hall",
  "Rivervale Primary School Hall",
  "Riverside Primary School Hall",
  "Riverside Secondary School Hall",
  "Rosyth School Hall",
  "Sembawang Primary School Hall",
  "Sembawang Secondary School Hall",
  "Seng Kang Primary School Hall",
  "Seng Kang Secondary School Hall",
  "Sengkang Green Primary School Hall",
  "Sengkang Sport Centre",
  "Sengkang Sport Hall",
  "Senja-Cashew Community Centre",
  "Senja-Cashew Sport Hall",
  "Serangoon Garden Secondary School Hall",
  "Serangoon Secondary School Hall",
  "Shuqun Primary School Hall",
  "Si Ling Primary School Hall",
  "Si Ling Secondary School Hall",
  "South View Primary School Hall",
  "Springdale Primary School Hall",
  "Springfield Secondary School Hall",
  "St. Anthony's Primary School Hall",
  "St. Gabriel's Secondary School Hall",
  "Swiss Cottage Secondary School Hall",
  "Tampines North Community Centre",
  "Tampines Sport Centre",
  "Tampines Sport Hall",
  "Tanjong Katong Primary School Hall",
  "Tanjong Katong Secondary School Hall",
  "Teck Ghee Primary School Hall",
  "Temasek Primary School Hall",
  "Temasek Secondary School Hall",
  "Toa Payoh Sport Centre",
  "Toa Payoh Sport Hall",
  "Townsville Primary School Hall",
  "Unity Primary School Hall",
  "Unity Secondary School Hall",
  "Waterway Primary School Hall",
  "Wellington Primary School Hall",
  "West Spring Primary School Hall",
  "West Spring Secondary School Hall",
  "West View Primary School Hall",
  "Westwood Primary School Hall",
  "Westwood Secondary School Hall",
  "White Sands Primary School Hall",
  "Whitley Secondary School Hall",
  "Woodgrove Primary School Hall",
  "Woodgrove Secondary School Hall",
  "Woodlands Primary School Hall",
  "Woodlands Ring Primary School Hall",
  "Woodlands Ring Secondary School Hall",
  "Woodlands Secondary School Hall",
  "Woodlands Sport Centre",
  "Woodlands Sport Hall",
  "Xinghua Primary School Hall",
  "Xinmin Primary School Hall",
  "Xinmin Secondary School Hall",
  "Yio Chu Kang Primary School Hall",
  "Yio Chu Kang Sport Centre",
  "Yio Chu Kang Sport Hall",
  "Yishun Primary School Hall",
  "Yishun Secondary School Hall",
  "Yishun Sport Centre",
  "Yishun Sport Hall",
  "Yishun Town Secondary School Hall",
  "Yuan Ching Secondary School Hall",
  "Yuhua Primary School Hall",
  "Yuhua Secondary School Hall",
  "Zhangde Primary School Hall",
  "Zhenghua Primary School Hall",
  "Zhenghua Secondary School Hall",
  "Zhonghua Primary School Hall",
  "Zhonghua Secondary School Hall",
];

if (typeof module !== "undefined" && module.exports) {
  module.exports = { VENUE_NAMES };
}
